### ISSUE TITLE
Specify communication API

### ISSUE THREAD

**Issue by rebinskiy** [ASQ-USI/asq-java-q-backend#1]
We should agree on the API to communicate with the server.

Precisely:

- [ ] List of functions available for the client
- [ ] JSON request and response format for each function
- [ ] Docker implementation for each function

**Comment by rebinskiy** [comment]
One file version (current) :

Request :
{
clientId : String,
fileName : String,
code : String,
timeLimitCompile : Integer,
timeLimitRuntime : Integer
}

Response:
{
clientId: String,
passed: Boolean,
output: String,
errorMessage: String,
timeOut: Boolean
}

**Comment by StKyr** [comment]
About the multiple files structure:

*_v: 1.2*

_Request:_
{
  clientId: String,
  file: File,
  compileTimeOut: Integer (in milliseconds),
  runTimeOut: Integer (in milliseconds),
  pathOfFileWithMain: String (valid relative path starting from top file)
}

where `[Object]` is an array of objects and 
File ={
      name: String,
     isDirectory: Boolean,
     code: String,
     subFiles: [File]
}

So the definition is recursive. Also mind that when `isDirectory` attribute is `True`, then `code` should be an empty string, where, when `isDirectory` is `False`, `subFiles` should be an empty array.

_Response_:
  _as previous_

**Comment by rebinskiy** [comment]
Are written in README
